server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
spring:
  datasource:
    url: jdbc:mysql://47.115.14.251:3306/pro?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: 47.115.14.251
    port: 6379
    database: 1

mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


